version: 1.3.{build}-dev
image: Visual Studio 2017
branches:
  only:
  - develop
init:
- tzutil /s "W. Europe Standard Time"
build_script:
- ps: .\build.ps1 -target test
after_test:
- ps: >-   
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./artifacts/dng.Syndication.Tests.trx))
