version: 1.3.{build}
image: Visual Studio 2017
init:
- tzutil /s "W. Europe Standard Time"
after_test:
- ps: >-   
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./artifacts/dng.Syndication.Tests.trx))

for:
-
  branches:
    only:
    - master
  build_script:
  - ps: .\build.ps1 -target publish

-
  branches:
    only:
    - develop
  build_script:
  - ps: .\build.ps1 -target test
